name: image_cropper_for_web
description: A Flutter plugin for Web supports cropping images
# repository: https://github.com/hnvn/flutter_image_cropper
# version: 6.0.2

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  image_cropper_platform_interface:
    git:
      url: https://github.com/ToKu404/flutter_image_cropper.git
      ref: master
      path: image_cropper_platform_interface

  js: ^0.6.4
  web: ">=0.5.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: image_cropper
    platforms:
      web:
        pluginClass: ImageCropperPlugin
        fileName: image_cropper_for_web.dart
