name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
# version: 8.0.2
# homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin
      web:
        default_package: image_cropper_for_web

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface:
    git:
      url: https://github.com/ToKu404/flutter_image_cropper.git
      ref: f883ff92fd13d17ab13bec1e8d5c4e70a7d682f1
      path: image_cropper_platform_interface
  image_cropper_for_web:
    git:
      url: https://github.com/ToKu404/flutter_image_cropper.git
      ref: c3c8cd5534ce1db2dd9030281fa0307f422f3fe2
      path: image_cropper_for_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
